version: "3"

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list

  venv:
    desc: Create a virtual environments
    cmds:
      - uv venv -p python3.9
      - uv pip install torch==2.1.2+cu121 torchaudio==2.1.2+cu121 torchvision==0.16.2+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
      - uv pip install -r requirements.txt --no-build-isolation

  download:
    desc: Download DEMAND+VCTK dataset
    cmds:
      - wget https://datashare.ed.ac.uk/download/DS_10283_1942.zip
      # manually unzip DS_10283_1942.zip

  downsample:
    desc: Downsample DEMAND+VCTK dataset
    cmds:
      - uv run .venv/bin/python downsampling.py

  make_json:
    desc: Make json file for DEMAND+VCTK dataset
    cmds:
      - uv run .venv/bin/python data/make_dataset_json.py --path data/DEMAND_VCTK_16k

  train:
    desc: Train Mamba-SEUNet
    cmds:
      - |
        uv run .venv/bin/python train.py \
          --exp_folder exp \
          --exp_name MambaSEUNet_emb_32 \
          --config recipes/Mamba-SEUNet/Mamba-SEUNet.yaml \
          2>&1 | tee train.log
